# Generated by Django 5.1.1 on 2024-10-21 13:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bmicalculation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BMICalculation',
            new_name='BMIRecord',
        ),
        migrations.AlterModelOptions(
            name='bmirecord',
            options={'ordering': ['-date']},
        ),
    ]
